apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-clusterip-service  # Name of service
spec:
  type: ClusterIP
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: 8081                          # Pod port
      targetPort: 8081                    # Container port
      