apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-nodeport-service # Name of service
spec:
  type: NodePort
  selector:
    app: k8s-app
  ports:
    - port: 8081                          # Pod port
      nodePort: 30180                     # Node machine port
      targetPort: 8081                    # Container port
      name: spring-boot-k8s-nodeport 
  